import React, { useRef } from 'react';
import { Printer, X, FileText } from 'lucide-react';
import { formatStockPrice } from '../../utils/priceFormat.ts';

interface FinancialSummaryPrintModalProps {
  dashboardData: any;
  salesHistory: any[];
  topSelling: any[];
  companySettings: any;
  currentUser: any;
  onClose: () => void;
}

export const FinancialSummaryPrintModal: React.FC<FinancialSummaryPrintModalProps> = ({
  dashboardData,
  salesHistory,
  topSelling,
  companySettings,
  currentUser,
  onClose,
}) => {
  const printAreaRef = useRef<HTMLDivElement>(null);

  const currencySymbol = companySettings?.currency_symbol || companySettings?.currencySymbol || 'Rs.';
  const storeName = companySettings?.company_name || companySettings?.companyName || 'Shoe Retail Store';
  const storeAddress = companySettings?.address || companySettings?.store_address || '';
  const storePhone = companySettings?.phone || companySettings?.store_phone || '';

  const today = dashboardData?.today || {};
  const todayRevenue = parseFloat(today.totalSales ?? today.revenue ?? 0);
  const todayProfit = parseFloat(today.profit ?? 0);
  const todayCount = today.invoiceCount ?? today.salesCount ?? 0;
  const todayCost = parseFloat(today.cost ?? 0);
  const profitMarginPercent =
    todayRevenue > 0 ? Math.round((todayProfit / todayRevenue) * 100).toString() : '0';

  // Compute payment breakdown from sales history
  const paymentBreakdown = salesHistory.reduce((acc: Record<string, number>, s: any) => {
    const method = (s.payment_method || 'Cash').toUpperCase();
    const amt = parseFloat(s.total_amount || 0);
    acc[method] = (acc[method] || 0) + amt;
    return acc;
  }, {});

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="app-modal-overlay">
      <div className="app-modal-container max-w-2xl w-full flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="bg-slate-900 dark:bg-gradient-to-r dark:from-purple-900 dark:via-indigo-950 dark:to-slate-900 text-white p-5 border-b border-slate-700/60 dark:border-purple-800/80 flex items-center justify-between no-print">
          <div className="flex items-center space-x-3">
            <div className="w-9 h-9 rounded-xl bg-blue-500/20 text-cyan-400 border border-blue-500/30 flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Daily Financial Closing Slip</h3>
              <p className="text-xs text-slate-400">Reconciliation and store analytics summary</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body / Printable Slip */}
        <div className="p-6 overflow-y-auto flex-1 text-slate-800 dark:text-slate-200">
          <div ref={printAreaRef} className="bg-white dark:bg-slate-950 p-6 rounded-xl border border-slate-200 dark:border-slate-800 space-y-6 print:border-none print:p-0">
            {/* Store Branding */}
            <div className="text-center pb-4 border-b border-slate-200 dark:border-slate-800 space-y-1">
              <h2 className="text-xl font-black tracking-tight text-slate-900 dark:text-white uppercase">
                {storeName}
              </h2>
              {storeAddress && <p className="text-xs text-slate-500 dark:text-slate-400">{storeAddress}</p>}
              {storePhone && <p className="text-xs text-slate-500 dark:text-slate-400">Tel: {storePhone}</p>}
              <div className="inline-block mt-2 px-3 py-1 rounded-full text-[11px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
                Daily Financial Summary &amp; Z-Report
              </div>
            </div>

            {/* Meta Details */}
            <div className="grid grid-cols-2 text-xs text-slate-600 dark:text-slate-400 gap-2 pb-3 border-b border-slate-200 dark:border-slate-800">
              <div>
                <span className="font-semibold text-slate-900 dark:text-white">Generated On: </span>
                {new Date().toLocaleString()}
              </div>
              <div className="text-right">
                <span className="font-semibold text-slate-900 dark:text-white">Generated By: </span>
                {currentUser?.name || currentUser?.username || 'Store Admin'}
              </div>
            </div>

            {/* Financial Metrics Summary */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Sales &amp; Profitability Breakdown
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-2">
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                  <span className="text-[10px] text-slate-500 dark:text-slate-400 font-bold uppercase">Gross Revenue</span>
                  <div className="text-sm font-black font-mono text-slate-900 dark:text-white mt-1">
                    {currencySymbol} {formatStockPrice(todayRevenue)}
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                  <span className="text-[10px] text-slate-500 dark:text-slate-400 font-bold uppercase">Receipts</span>
                  <div className="text-sm font-black font-mono text-slate-900 dark:text-white mt-1">
                    {todayCount} Invoices
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                  <span className="text-[10px] text-slate-500 dark:text-slate-400 font-bold uppercase">Estimated COGS</span>
                  <div className="text-sm font-black font-mono text-slate-900 dark:text-white mt-1">
                    {currencySymbol} {formatStockPrice(todayCost)}
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-blue-50 dark:bg-blue-950/60 border border-blue-200 dark:border-blue-900/50">
                  <span className="text-[10px] text-blue-700 dark:text-cyan-400 font-bold uppercase">Net Gross Profit</span>
                  <div className="text-sm font-black font-mono text-blue-700 dark:text-cyan-400 mt-1">
                    {currencySymbol} {formatStockPrice(todayProfit)}
                  </div>
                  <span className="text-[9.5px] text-slate-500 dark:text-slate-400 font-medium">Margin: {profitMarginPercent}%</span>
                </div>
              </div>
            </div>

            {/* Payment Method Distribution */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Payment Collections Reconciliation
              </h4>
              <div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden">
                <table className="w-full text-xs text-left">
                  <thead className="bg-slate-50 dark:bg-gradient-to-r dark:from-purple-900/90 dark:via-indigo-950/85 dark:to-slate-900 text-slate-700 dark:text-white font-semibold border-b border-slate-200 dark:border-purple-800/80">
                    <tr>
                      <th className="py-2 px-3">Payment Tender</th>
                      <th className="py-2 px-3 text-right">Amount Collected</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800 font-mono">
                    {Object.keys(paymentBreakdown).length === 0 ? (
                      <tr>
                        <td colSpan={2} className="py-3 px-3 text-center text-slate-400">No payment data recorded today</td>
                      </tr>
                    ) : (
                      Object.entries(paymentBreakdown).map(([method, amt]) => (
                        <tr key={method}>
                          <td className="py-2 px-3 font-sans font-medium text-slate-800 dark:text-slate-200">{method}</td>
                          <td className="py-2 px-3 text-right font-bold text-slate-900 dark:text-white">
                            {currencySymbol} {formatStockPrice(amt as number)}
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Top Footwear Movers */}
            {topSelling && topSelling.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                  Top Moving Footwear Models
                </h4>
                <div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden">
                  <table className="w-full text-xs text-left">
                    <thead className="bg-slate-50 dark:bg-gradient-to-r dark:from-purple-900/90 dark:via-indigo-950/85 dark:to-slate-900 text-slate-700 dark:text-white font-semibold border-b border-slate-200 dark:border-purple-800/80">
                      <tr>
                        <th className="py-2 px-3">Article / Model</th>
                        <th className="py-2 px-3 text-center">Pairs Sold</th>
                        <th className="py-2 px-3 text-right">Total Value</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                      {topSelling.slice(0, 5).map((ts: any, i: number) => (
                        <tr key={i}>
                          <td className="py-2 px-3">
                            <span className="font-semibold text-slate-900 dark:text-white">{ts.article || ts.productName || ts.name}</span>
                            {ts.sku && <span className="ml-1.5 text-[10px] text-slate-400 font-mono">({ts.sku})</span>}
                          </td>
                          <td className="py-2 px-3 text-center font-mono font-bold">{ts.totalQuantitySold || ts.unitsSold || 0}</td>
                          <td className="py-2 px-3 text-right font-mono font-bold text-slate-900 dark:text-white">
                            {currencySymbol} {formatStockPrice(ts.totalRevenue || 0)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Footnote */}
            <div className="pt-4 border-t border-slate-200 dark:border-slate-800 text-center text-[10.5px] text-slate-400 space-y-1">
              <p>Certified accurate according to active POS database transactions.</p>
              <p className="font-mono">End of Report • {storeName}</p>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-50 dark:bg-gradient-to-r dark:from-purple-900/90 dark:via-indigo-950/85 dark:to-slate-900 border-t border-slate-200 dark:border-purple-800/80 flex items-center justify-between no-print">
          <button
            type="button"
            onClick={onClose}
            className="btn-secondary px-4 py-2 text-xs font-semibold rounded-xl cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handlePrint}
            className="bg-gradient-to-r from-purple-600 via-indigo-600 to-purple-700 hover:from-purple-700 hover:via-indigo-700 hover:to-purple-800 text-white border border-purple-400/40 dark:border-purple-400/50 shadow-md shadow-purple-600/25 dark:shadow-[0_0_14px_rgba(147,51,234,0.3)] font-bold px-5 py-2 rounded-xl text-xs flex items-center space-x-2 transition-all cursor-pointer active:scale-95"
          >
            <Printer className="w-4 h-4" />
            <span>Print Financial Summary</span>
          </button>
        </div>
      </div>
    </div>
  );
};
